package ser;


/**
* TaxApp/Tax.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from taxproj.idl
* Monday, April 27, 2020 7:37:14 PM EDT
*/

public interface Tax extends TaxOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Tax
