package ser;


/**
* TaxApp/TaxHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from taxproj.idl
* Monday, April 27, 2020 7:37:14 PM EDT
*/

abstract public class TaxHelper
{
  private static String  _id = "IDL:TaxApp/Tax:1.0";

  public static void insert (org.omg.CORBA.Any a, ser.Tax that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ser.Tax extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ser.TaxHelper.id (), "Tax");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ser.Tax read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_TaxStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ser.Tax value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ser.Tax narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ser.Tax)
      return (ser.Tax)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ser._TaxStub stub = new ser._TaxStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ser.Tax unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ser.Tax)
      return (ser.Tax)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ser._TaxStub stub = new ser._TaxStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
