package ser;

/**
* TaxApp/TaxHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from taxproj.idl
* Monday, April 27, 2020 7:37:14 PM EDT
*/

public final class TaxHolder implements org.omg.CORBA.portable.Streamable
{
  public ser.Tax value = null;

  public TaxHolder ()
  {
  }

  public TaxHolder (ser.Tax initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ser.TaxHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ser.TaxHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ser.TaxHelper.type ();
  }

}
