package ser;


/**
* TaxApp/TaxPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from taxproj.idl
* Monday, April 27, 2020 7:37:14 PM EDT
*/

public abstract class TaxPOA extends org.omg.PortableServer.Servant
 implements ser.TaxOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("calculateTax", new java.lang.Integer (0));
    _methods.put ("calculatetaxbracket", new java.lang.Integer (1));
    _methods.put ("shutdown", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // TaxApp/Tax/calculateTax
       {
         double Sal = in.read_double ();
         double taxR = in.read_double ();
         double $result = (double)0;
         $result = this.findTax (Sal, taxR);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 1:  // TaxApp/Tax/calculatetaxbracket
       {
         double bracket = in.read_double ();
         double $result = (double)0;
         $result = this.findbracket (bracket);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 2:  // TaxApp/Tax/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:TaxApp/Tax:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Tax _this() 
  {
    return TaxHelper.narrow(
    super._this_object());
  }

  public Tax _this(org.omg.CORBA.ORB orb) 
  {
    return TaxHelper.narrow(
    super._this_object(orb));
  }


} // class TaxPOA
